apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ui-binding
  namespace: default
subjects:
- kind: ServiceAccount
  name: ui-sa
roleRef:
  kind: Role
  name: ui-role
  apiGroup: rbac.authorization.k8s.io
